//
// Created by viniman on 22/06/19.
//

#ifndef AI_MAZE_SEARCH_ALGORITHMS_SEARCHALGORITHM_H
#define AI_MAZE_SEARCH_ALGORITHMS_SEARCHALGORITHM_H


class SearchAlgorithm {

};


#endif //AI_MAZE_SEARCH_ALGORITHMS_SEARCHALGORITHM_H
